import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
  },
  Moadlview: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  myarea: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    paddingRight: 10,
  },
  ModalContent: {
    backgroundColor: 'white',
    height: '80%',
    width: '100%',
  },
  mask: {
    width: '100%',
    flex: 1,
    backgroundColor: 'black',
    opacity: 0.5,
  },
  Popheader: {
    paddingHorizontal: 10,
    alignItems: 'center',
    width: '100%',
    height: 40,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  Popheaderrigth: {
    flex: 1,
    justifyContent: 'flex-end',
    flexDirection: 'row',
    height: 40,
    alignItems: 'center',
  },
  Buttonidor: {
    width: 'auto',
    height: 'auto',
    padding: 5,
    fontSize: 13,
    borderRadius: 15,
    paddingHorizontal: 15,
    color: 'rgb(105, 166, 252)',
    backgroundColor: 'rgb(245,245,245)',
    marginRight: 10,
  },
  Buttonimg: {
    width: 25,
    height: 25,
    resizeMode: 'contain',
    transform: [{rotate: '90deg'}],
  },
  recommed: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    padding: 10,
    height: 'auto',
  },
  recommenditem: {
    justifyContent: 'center',
    alignItems: 'center',
    fontWeight: 'bold',
    marginBottom: 10,
    width: 90,
    marginHorizontal: 3,
    height: 40,
    backgroundColor: 'white',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgb(230,230,230)',
  },
  defaultitem: {
    flexDirection: 'row',
    backgroundColor: 'rgb(245,245,245)',
    borderColor: 'white',
  },
  text: {
    color: 'black',
    fontSize: 16,
  },
});
